# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-08 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_loan_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='covenant',
            name='comparison',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
